### ISSUE TITLE
Documentation improvement required.

### ISSUE THREAD

**Issue by OrangeBean** [stewartml/gherkin-jest#3]
Hi there,

I like your project. Thanks for doing this. 
I'm new comer here. Getting onboard with this setup is a bot hard. Documentation improvement is required. If you can improve readme and explain what is what - would be great. Example project to illustrate how to set it up also would be great.

Like when you saying "Then, add to your jest config:" is a bit like a black magic to me.

**Comment by alexanderbird** [comment]
I actually found the documentation to be complete enough to get it up and running - it might be helpful if you could give a short list of areas that you feel the README is lacking? 

As for the jest config - what part of that is black magic to you? Maybe I can help you understand how to set it up? If there really is something critical that’s missing from the readme, maybe you could update it yourself and make a pull request?

@stewartml, I maybe should have checked before submitting one, but are you open to pull requests? And by the way, thanks for this project! I found it took way less to set up than cucumberjs, it’s quite nice.

**Comment by sjmeverett** [comment]
Thanks for your interest. I guess the readme assumes familiarity with jest, perhaps it could do with some links to jest docs. Could you be more specific?

Yes, PRs welcome. I'm generally rather busy though, don't be offended if I don't respond straight away :)

**Comment by sjmeverett** [comment]
I'm going to close this.  Please feel free to re-open it if you have specific suggestions.  A documentation improvement is coming anyway.
