### ISSUE TITLE
0.11.0 fails to find tests

### ISSUE THREAD

**Issue by rdickert** [stewartml/gherkin-jest#4]
Great project, thanks for publishing this! 

I ran into an issue in 0.11.0 where it appears that cucumber tries to run tests before the support file has run. Partial output:

```sh
  ● Feature: using feature files in jest › a simple arithmetic test

    Could not find matching rule: I have numbers 3 and 4

      at Cucumber.rule (../../node_modules/stucumber/src/lib/cucumber.ts:118:11)
      at cucumber.enterScenario.then (test.feature:9:11)
          at <anonymous>
      at process._tickCallback (../../internal/process/next_tick.js:188:7)
```

**To reproduce**, clone the repo, run `yarn` and `yarn test`.

This issue is not present on 0.10.0 (checking out that branch and rerunning yarn fixes it), so I guess the issue is in stucumber, but posting here since this is the controlling lib and it could also be a docs/setup issue.

**Comment by sjmeverett** [comment]
Thanks @rdickert, sorry for the delay.  Been busy with work and Christmas stuff!  Will be picking this up today hopefully.

**Comment by dash1291** [comment]
I'm facing this issue with v0.16.0. I'm not sure whether it's a config/setup issue or a bug.
