### ISSUE TITLE
Add support for `Background`?

### ISSUE THREAD

**Issue by alexanderbird** [stewartml/gherkin-jest#7]
If you've got some time to add features, it would be helpful to have support for the `Background` block - https://github.com/cucumber/cucumber/wiki/Background

I would think it would make sense to generate a jasmine `beforeEach` block corresponding to the gherkin `Background`, but it could also be done by adding the `Background` steps to each scenario in the feature.

**Comment by sjmeverett** [comment]
Hi Alexander. I needed this too, I've implemented it here https://github.com/stewartml/stucumber/pull/2

Will merge soon.

**Comment by sjmeverett** [comment]
Merged :)
