### ISSUE TITLE
Data tables do not reach step in `defineRule`

### ISSUE THREAD

**Issue by rdickert** [stewartml/gherkin-jest#8]
In rules code, the data table from a step is not being passed to `cucumber.defineRule()` as described in the readme.

To reproduce: Copy the [code from the stucumber readme](https://www.npmjs.com/package/stucumber#data-tables). Result: 

```
  ● Feature: lots of data › lots of data

    TypeError: Cannot read property 'asObjects' of undefined

       99 |
      100 | cucumber.defineRule('lots of data', (world, table, two, three) => {
    > 101 |   const obj = table.asObjects();
```

@stewartml I started to troubleshoot, but I'm guessing you'll be able to trace this quickly. Let me know if you need anything

**Comment by sjmeverett** [comment]
Hi, sorry for the delay.  Fixed by: https://github.com/stewartml/stucumber/commit/632afce6f548d7d0ea168c981811a062f9582096#diff-7b43b007342dd40b6b4a56010ea03084R90
